Numpy tutorial:Assignment

1.Example question

In [ ]:
import numpy as np

list = [1, 3, 8, 9]
arr = np.array(object=list)


print(arr)

[1 3 8 9]


Exercise 1:

1.. Is there any difference in the data type of variables list_ and array_list? If there is then write
a code
to print the data types of both the variables.


In [ ]:
import numpy as np
list = [3, 6, 9, 10]
arr = np.array(list)
print(type(list))
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


Exercise 2:

2.Write a code to print the data type of each and every element of both the variables list_ and
arra_list

In [ ]:
import numpy as np
list = ["grapes", "banana","orange", "apple"]
arr_list = np.array(list)
print("array elements:")
for i in arr_list:
  print(type(i))



print("list element:")
for i in list:
  print(type(i))

array elements:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
list element:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_
and
arra_list? If so then print the data types of each and every element present in both the variables,
list_
and arra_list.

In [ ]:
import numpy as np

list_ = [6,4,7,10]
arr_list = np.array(object=list_,dtype = int)
for i in list_:
  print(type(i))

for i in arr_list:
  print(type(i))

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


2.Example code:

In [ ]:
import numpy as np

num_list = ([1,6,9],[3,9,10])
num_arr =np.array(object = num_list)
print(num_arr)

[[ 1  6  9]
 [ 3  9 10]]


4.Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [ ]:
import numpy as np
list = ([1,3,9],[5,4,8])
arr = np.array(object = list)
print("shape:",arr.shape)
print("size:",arr.size)

shape: (2, 3)
size: 6


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy
array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]


In [ ]:
import numpy as np
list = ([2,6,9],[4,9,10],[49,30,20])
arr = np.zeros((3,3))
print(arr)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


6.Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.

In [ ]:
import numpy as np
list = [2,5,9],[4,10,9],[6,9,5]
arr = np.identity((5))
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
